import type { Selectable, Updateable, Insertable } from "kysely";
import type { Todo } from "./db-types.js";

export type GetPost = Selectable<Todo>;
export type CreatePost = Insertable<Todo>;
export type CreatePostInput = Omit<Insertable<Todo>, "id" | "timestamp">; // id and timestamp will be autogenerated and thus should not be manually set

export type UpdatePost = Updateable<Todo>;
